# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: buildpacks/github-actions/setup-pack@v5.0.0

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: pack build ghcr.io/anthonydahanne/newsy-mastodon --buildpack paketo-buildpacks/go --builder paketobuildpacks/builder:base --publish

    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy image
      run: flyctl deploy --image ghcr.io/anthonydahanne/newsy-mastodon
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

